# Generated by Django 6.0.2 on 2026-02-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackOfFlashCards',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('level_of_knowledge', models.IntegerField(default=0)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_cards', to='flash_cards.stackofflashcards')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stackofflashcards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='flash_cards.user'),
        ),
    ]
