# Generated by Django 6.0.2 on 2026-02-20 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8af04bd3-917d-44b5-bc99-0be99fa6a52f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stackofflashcards',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8af04bd3-917d-44b5-bc99-0be99fa6a52f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8af04bd3-917d-44b5-bc99-0be99fa6a52f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
